apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.support.scheduler}}
  name: {{.Values.edgex.app.support.scheduler}}
spec:
  ports:
  - name: "59861"
    port: 59861
    targetPort: 59861
    nodePort: {{.Values.expose.nodePort.support.scheduler}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.support.scheduler}}
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}
