apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.support.rulesengine}}
  name: {{.Values.edgex.app.support.rulesengine}}
spec:
  ports:
  - name: "59720"
    port: 59720
    targetPort: 59720
    nodePort: {{.Values.expose.nodePort.support.rulesengine}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.support.rulesengine}}
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}
