apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.support.rulesengine}}
  name: {{.Values.edgex.app.support.rulesengine}}
spec:
  replicas: {{.Values.edgex.replicas.support.rulesengine}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.support.rulesengine}}
  strategy: {}
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.support.rulesengine}}
    spec:
      containers:
      - name: {{.Values.edgex.app.support.rulesengine}}
        image: {{.Values.edgex.image.support.rulesengine.repository}}:{{.Values.edgex.image.support.rulesengine.tag}}
        imagePullPolicy: {{.Values.edgex.image.support.rulesengine.pullPolicy}}
        ports:
        - containerPort: 59720
        - containerPort: 20498
        env:
#        - name: KUIPER__DEBUG
#          value: "true"
        - name: KUIPER__BASIC__CONSOLELOG
          value: "true"
        - name: KUIPER__BASIC__RESTPORT
          value: "59720"
        - name: EDGEX__DEFAULT__SERVER
          value: {{.Values.edgex.app.redis}}
        - name: EDGEX__DEFAULT__TYPE
          value: "redis"
        - name: EDGEX__DEFAULT__TOPIC
          value: "rules-events"
        - name: EDGEX__DEFAULT__PROTOCOL
          value: "redis"
        - name: EDGEX__DEFAULT__PORT
          value: "6379"
        livenessProbe:
          tcpSocket:
            port: 59720
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 59720
          periodSeconds: 5
      {{- if .Values.edgex.resources.support.rulesengine.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.support.rulesengine.limits.memory }}
            cpu: {{ .Values.edgex.resources.support.rulesengine.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.support.rulesengine.requests.memory }}
            cpu: {{ .Values.edgex.resources.support.rulesengine.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.support.rulesengine}}
      restartPolicy: Always
status: {}
