apiVersion: v1
kind: ConfigMap
metadata:
  name: edgex-common-variables
data:
  EDGEX_SECURITY_SECRET_STORE: "false"
  REGISTRY_HOST: {{.Values.edgex.app.core.consul}}
  CLIENTS_CORE_COMMAND_HOST: {{.Values.edgex.app.core.command}}
  CLIENTS_CORE_DATA_HOST: {{.Values.edgex.app.core.data}}
  CLIENTS_CORE_METADATA_HOST: {{.Values.edgex.app.core.metadata}}
  CLIENTS_SUPPORT_NOTIFICATIONS_HOST: {{.Values.edgex.app.support.notifications}}
  CLIENTS_SUPPORT_SCHEDULER_HOST: {{.Values.edgex.app.support.scheduler}}
  DATABASES_PRIMARY_HOST: {{.Values.edgex.app.redis}}
  MESSAGEQUEUE_HOST: {{.Values.edgex.app.redis}}
