apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-config
spec:
{{- if (eq "-" .Values.persistence.storageclassname) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageclassname }}"
{{- end }}
  accessModes:
  - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.consul_config | quote }}
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data
spec:
{{- if (eq "-" .Values.persistence.storageclassname) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageclassname }}"
{{- end }}
  accessModes:
  - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.consul_data | quote }}
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
spec:
{{- if (eq "-" .Values.persistence.storageclassname) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageclassname }}"
{{- end }}
  accessModes:
  - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.db_data | quote }}
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-data
spec:
{{- if (eq "-" .Values.persistence.storageclassname) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageclassname }}"
{{- end }}        
  accessModes:
  - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.log_data | quote }}
status: {}
