apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-config
spec:
{{- if (eq "-" .Values.persistence.storageclassname) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageclassname }}"
{{- end }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.persistence.size.consul-config }}"
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data
spec:
{{- if (eq "-" .Values.persistence.storageclassname) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageclassname }}"
{{- end }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.persistence.size.consul-data }}"
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
spec:
{{- if (eq "-" .Values.persistence.storageclassname) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageclassname }}"
{{- end }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.persistence.size.db-data }}"
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-data
spec:
{{- if (eq "-" .Values.persistence.storageclassname) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageclassname }}"
{{- end }}        
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.persistence.size.log-data }}"
status: {}
