apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.core.data}}
  name: {{.Values.edgex.app.core.data}}
spec:
  replicas: {{.Values.edgex.replicas.core.data}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.core.data}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.core.data}}
    spec:
      containers:
      - name: {{.Values.edgex.app.core.data}}
        image: {{.Values.edgex.image.core.data.repository}}:{{.Values.edgex.image.core.data.tag}}
        imagePullPolicy: {{.Values.edgex.image.core.data.pullPolicy}}
        volumeMounts:
          - name: config
            mountPath: /res
        ports:
        - containerPort: 59880
        - containerPort: 5563
        env:
        - name: SERVICE_HOST
          value: {{.Values.edgex.app.core.data}}
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        readinessProbe:
          httpGet:
            path: /api/v2/ping
            port: 59880
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v2/ping
            port: 59880
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
      {{- if .Values.edgex.resources.core.data.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.core.data.limits.memory }}
            cpu: {{ .Values.edgex.resources.core.data.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.core.data.requests.memory }}
            cpu: {{ .Values.edgex.resources.core.data.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.core.data}}
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: {{.Values.edgex.app.core.data}}
status: {}
