apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.appservice.rules}}
  name: {{.Values.edgex.app.appservice.rules}}
spec:
  replicas: {{.Values.edgex.replicas.appservice.rules}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.appservice.rules}}
  strategy: {}
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.appservice.rules}}
    spec:
      containers:
      - name: {{.Values.edgex.app.appservice.rules}}
        image: {{.Values.edgex.image.appservice.rules.repository}}:{{.Values.edgex.image.appservice.rules.tag}}
        imagePullPolicy: {{.Values.edgex.image.appservice.rules.pullPolicy}}
        ports:
        - containerPort: 59701
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        env:
        - name: EDGEX_PROFILE
          value: "rules-engine"
        - name: SERVICE_HOST
          value: {{.Values.edgex.app.appservice.rules}}
        - name: SERVICE_PORT
          value: "59701"
        - name: TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST
          value: {{.Values.edgex.app.redis}}
        - name: TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST
          value: {{.Values.edgex.app.redis}}
        readinessProbe:
          httpGet:
            path: /api/v2/ping
            port: 59701
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v2/ping
            port: 59701
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
      {{- if .Values.edgex.resources.appservice.rules.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.appservice.rules.limits.memory }}
            cpu: {{ .Values.edgex.resources.appservice.rules.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.appservice.rules.requests.memory }}
            cpu: {{ .Values.edgex.resources.appservice.rules.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.appservice.rules}}
      restartPolicy: Always
status: {}
