apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.device.rest}}
  name: {{.Values.edgex.app.device.rest}}
spec:
  ports:
  - name: "59986"
    port: 59986
    targetPort: 59986
    nodePort: {{.Values.expose.nodePort.device.rest}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.device.rest}}
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}
